### ISSUE TITLE
The web site

### ISSUE THREAD

**Issue by richardbeare** [richardbeare/GeospatialStroke#26]
@SymbolixAU the other major job - assembling this stuff into a sensible website. I only know the basics, so I'm hoping you have some ideas on how to mash it into a github hosted version, while also allowing someone to clone and play around. Feel free to change names etc. I presume we'll have to run some R code by hand somewhere to produce the html.

**Comment by SymbolixAU** [comment]
@richardbeare ok done, I think it worked.

**Comment by richardbeare** [comment]
@SymbolixAU Just clicked the link. Hopefully it will update the forks too.

**Comment by richardbeare** [comment]
Done - [site live](https://richardbeare.github.io/GeospatialStroke)
